### ISSUE TITLE
Phocus Recipe Not Updating 

### ISSUE THREAD

**Issue by TekTekkers** [autopkg/neilmartin83-recipes#10]
Hi

Phocus Munki recipe is not pulling the latest version
is there something I  have missed

`autopkg run -v /Users/admin/Library/AutoPkg/RecipeOverrides/Phocus.munki.recipe
Processing /Users/admin/Library/AutoPkg/RecipeOverrides/Phocus.munki.recipe...
URLTextSearcher
URLTextSearcher: Found matching text (match): https://cdn.hasselblad.com/software/Phocus-for-Mac/3.5.4/Phocus-3.5.4.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/admin/Library/AutoPkg/Cache/local.munki.Phocus/downloads/Phocus.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/admin/Library/AutoPkg/Cache/local.munki.Phocus/downloads/Phocus.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.2pmkY9/Phocus.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.2pmkY9/Phocus.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.2pmkY9/Phocus.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Versioner
Versioner: Mounted disk image /Users/admin/Library/AutoPkg/Cache/local.munki.Phocus/downloads/Phocus.dmg
Versioner: Found version 3.5.4 in file /Users/admin/Library/AutoPkg/Cache/local.munki.Phocus/downloads/Phocus.dmg/Phocus.app/Contents/Info.plist
MunkiImporter
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:     plugin: FileRepo
MunkiImporter:      repo: /Library/Server/Web/Data/Sites/Default/repo
MunkiImporter: Item Phocus.dmg already exists in the munki repo as pkgs/apps/Phocus/Phocus-3.5.4.dmg.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.Phocus/receipts/Phocus.munki-receipt-20210402-234018.plist`

**Comment by neilmartin83** [comment]
Fixed!
