### ISSUE TITLE
Add "include_prereleases" variable to macOSLAPS.download.recipe

### ISSUE THREAD

**Issue by pnerum** [autopkg/neilmartin83-recipes#23]
Hi Neil,

We want to be able to use the "include_prereleases" variable for the GitHubReleasesInfoProvider processor in your download recipe: https://github.com/autopkg/neilmartin83-recipes/blob/master/macOSLAPS/macOSLAPS.download.recipe
More info around the key is found here: https://github.com/autopkg/autopkg/wiki/Processor-GitHubReleasesInfoProvider

We use the https://github.com/autopkg/dataJAR-recipes/blob/master/macOSLAPS/macOSLAPS.munki.recipe recipe and would like to be able to test the beta versions of macOSLAPS.

We use this same variable for the Zentral swiftDialog recipe for example: https://github.com/autopkg/zentral-recipes/blob/master/swiftDialog/swiftDialog.download.recipe

All best,

Patrick van Nerum

**Comment by neilmartin83** [comment]
Hey Patrick,

Thank you - should be sorted now in https://github.com/autopkg/neilmartin83-recipes/commit/9cb47d5a109d636cedf18cc3cd5b164853007058

Could you please test and let me know how it goes?


Cheers!

**Comment by pnerum** [comment]
Works like a charm:

`The following new items were imported into Munki:
    Name       Version  Catalogs  Pkginfo Path                                    Pkg Repo Path                                            Icon Repo Path  
    ----       -------  --------  ------------                                    -------------                                            --------------  
    macOSLAPS  4.0.0    testing   apps/macoslaps/macOSLAPS/macOSLAPS-4.0.0.plist  apps/macoslaps/macOSLAPS/macOSLAPS-4.0.0(845)-4.0.0.pkg                  `

Thank you very much!
